# --- build stage ---
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY dotnet-test.csproj ./
COPY certs/ /etc/pki/ca-trust/source/anchors/
#RUN update-ca-trust extract
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

# --- runtime stage ---
FROM mcr.microsoft.com/dotnet/runtime:9.0-bookworm-slim AS runtime
# ca-certificates is present on this image; ensure up to date:
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /app/publish ./

# Env options:
# - WELL_KNOWN_URL                (full URL) OR
# - KEYCLOAK_BASE_URL + KEYCLOAK_REALM
# - ALLOW_INSECURE_HTTP=true      (only if you must talk to http://)
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

ENTRYPOINT ["dotnet", "dotnet-test.dll"]